### ISSUE TITLE
carto color update process? need an idea

### ISSUE THREAD

**Issue by makella** [CartoDB/CartoColor#10]
@javisantana 

can you help me understand a little better how we will do updates with carto colors?

this will really help me with a few things:
- adding new palettes
- organizing palettes
- if a palette that is currently in production is not working well, the ability to remove or adjust and get that read back into the production environment.

If I know the update cycle (like when we can push in new revisions to production) that will really help me prioritize my own workflows.

thanks!

**Comment by javisantana** [comment]
THis is basically a library so when you update it we need to update in the builder. Ideally you should work on it and create versions when you feel you have something "stable" or "finished"

**Comment by makella** [comment]
ok, thanks! and so do i just write you an issue here for that or is it better in cartodb/cartodb?

let me know what's easiest and most efficient.

**Comment by saleiva** [comment]
here is good

**Comment by makella** [comment]
ok! thank you!!

i will be sure to document any changes and notify you guys here.

i will not be changing the names for the ones we already have which will avoid future broken things! :)
