### ISSUE TITLE
License?

### ISSUE THREAD

**Issue by nyalldawson** [CartoDB/CartoColor#26]
Love these color schemes - nice work! I can't find any licensing information here. Do you have objections to them being used in non carto projects?

**Comment by makella** [comment]
@nyalldawson thank you! and great question.

CARTOColors are made available under a [Creative Commons Attribution](https://creativecommons.org/licenses/by/3.0/us/) license.

We'll be updating our landing page and website with this information very soon!

**Comment by clhenrick** [comment]
@makella is there a way CARTO could make the NPM package MIT licensed though? That would allow more developers to use the schemes programatically. Thanks!
