### ISSUE TITLE
JSON incorrectly grouping # of colors per category

### ISSUE THREAD

**Issue by rgdonohue** [CartoDB/CartoColor#35]
Within the [colors.js](https://github.com/CartoDB/CartoColor/blob/master/cartocolor.js) file, around line 1233, the number of colors per classification number # appears off. Three colors within '2', four within '3', etc.

![image](https://user-images.githubusercontent.com/1952205/28434024-2c1f5446-6d4b-11e7-893a-59070bc14bf3.png)

**Comment by makella** [comment]
@rgdonohue heyy! sorry i didn't see this sooner.

so what we do is for each set of category colors is add a neutral color for "other" it is designed this way to work with Builder.

more details here:
https://github.com/CartoDB/cartodb/issues/11065

**Comment by rgdonohue** [comment]
@makella, ah that makes sense. Thank you. We're pulling cartocolor.js into some scripts this week for a new New Maps Plus course!

**Comment by makella** [comment]
oh so awesome!! would love to see anything that comes out of it!
