### ISSUE TITLE
R package of CartoColor

### ISSUE THREAD

**Issue by nuest** [CartoDB/CartoColor#36]
Hi! Beatiful palettes you have there. Are you aware of an R (rstats, R-project) package developments providing these colors in R?

Just don't want to replicate existing work, it's not on the official repository (CRAN) yet. RColorBrewers is quite often used (see reverse depends/imports/suggests [here](https://cran.r-project.org/web/packages/RColorBrewer/)), so the CartoColors could bring a nice new touch to the R mapping community.

**Comment by andy-esch** [comment]
You can find them in the Python package palettable: https://jiffyclub.github.io/palettable/cartocolors/ ;)

**Comment by Nowosad** [comment]
Hi @nuest @andy-esch - I'm working on it now - https://github.com/Nowosad/rcartocolor
