### ISSUE TITLE
Attribute Cindy Brewer

### ISSUE THREAD

**Issue by jsanz** [CartoDB/CartoColor#37]
It'd be nice to give an explicit attribution for Cindy Brewer ramps somewhere, just with a link to [her univ page](http://www.geog.psu.edu/people/brewer-cynthia) or the colorbrewer app.

**Comment by makella** [comment]
how's this?

https://github.com/CartoDB/CartoColor/blob/master/README.md#creditsadditional-information

**Comment by makella** [comment]
closing but reopen if you think i should add more.

thanks, jorge!

**Comment by jsanz** [comment]
Excellent, thanks Mamata!

--
Jorge Sanz
CARTO - Predict through location
