### ISSUE TITLE
Modifying ramps

### ISSUE THREAD

**Issue by makella** [CartoDB/CartoColor#5]
@javisantana @rochoa @fdansv @saleiva 

Hey guys,

I am modifying the color ramps. Getting rid of ones that I don't think we need and that aren't that good. Also, the ones that I want to keep, I am making them better, stronger to support our maps. Now that I've seen some of them being used on different maps, its time to make some modifications.

I'm not sure what this means for turbocarto, autostyling, etc.

What do you think the best way to do this is?

I just want to update this with some new ones, delete the old ones, and then give them better names -- especially the sequential palettes.

**Comment by rochoa** [comment]
We will have to update the dependency yo use those new ramps.

About the ones that you plan to remove: if someone are using them their maps will break, but it's better to take the decision now than wait until is too late.

**Comment by makella** [comment]
@rochoa @dgaubert 

so i kept everything that people have been using -- i also didn't change their names so everything with those should be ok.

https://github.com/CartoDB/research/wiki/Sequential-Palettes-NEW

i still need to modify some for the diverging set. 

can we plan maybe for the end of the week?

i'll make a branch here with the new ones and when everyone is ready maybe we can do the update?

thanks!
mamata
