### ISSUE TITLE
added colorbrewer palettes

### ISSUE THREAD

**Issue by makella** [CartoDB/CartoColor#7]
@javisantana 

i added the colorbrewer palettes.

they are all backwards. we need to flip them like the others.

pushed to master.

**Comment by javisantana** [comment]
if they are backwards I'm thinking if we should follow the same pattern. At the end we did this library following the colorbrewer pattern

In the other hand we should not copy&paste palettes, we should have colorbrewer as a dependency

**Comment by makella** [comment]
this is really confusing because the palettes are being read in backwards in the builder right now. the first color is being assigned to the lowest value and the lightest color the highest value. If we do the light/dark basemap dependant styling, then this would be the pattern we want for the dark basemap. But for the light basemap, (and general practice) is the opposite.

**Comment by saleiva** [comment]
Adding colorbrewer palettes to the builder is important as it helps to maintain backwards compatibility

**Comment by javisantana** [comment]
they are there

**Comment by makella** [comment]
I'm still seeing way more Brewer palettes than we had defined in cartocolor.js

If you guys want them all in there, no problem but if we could make a decision together about that and then figure out a way to separate them from Carto Colors that would be my preference.

thanks!

**Comment by javisantana** [comment]
umh, I have a fix locally for that, not yet in production
